title: Confessions of a Resurrected Programmer
author: Deslea
email: deslea@deslea.com
description: > # this means to ignore newlines until "baseurl:"
 A dot com boomer returns to programming. Results are variable.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  deslea # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
